In [2]:
import pandas as pd 
df = pd.read_csv('學生成績.csv')
df

    學號   姓名    國    英   數   社    自   總分    平均
0    1  王德城   99   56  67  85   78  385  77.0
1    2  游詩亞   80   67  90  97   51  385  77.0
2    3  李佳彥   63   70  51  90   87  361  72.2
3    4  陳倩潔   65   97  56  58   69  345  69.0
4    5  林向鈺   88   90  93  54   71  396  79.2
5    6  黃佩芬   77   73  98  55  100  403  80.6
6    7  楊健麟   95   89  54  90   95  423  84.6
7    8  陳信宏   80   66  64  63   99  372  74.4
8    9  白美珍   84   92  64  74   52  366  73.2
9   10  黃嘉琪   82   98  86  91   51  408  81.6
10  11  陳文賢   59   87  69  52   68  335  67.0
11  12  陳家年   76  100  61  59   96  392  78.4
12  13  錢佩豪   57   58  71  74   71  331  66.2
13  14  鄭佳玲   83   59  96  72   82  392  78.4
14  15  蔡嘉音   92   50  68  70   64  344  68.8
15  16  魏秋萍   89  100  82  68   85  424  84.8
16  17  鞠冠宇   54   91  71  97   88  401  80.2
17  18  李慈啟   86   90  66  55   74  371  74.2
18  19  楊綺芬   61   78  97  68   75  379  75.8
19  20  鄭奇翰   58   76  51  63   86  334  66.8
20  21  林俊翔   64   99  60  65   70  358  71.6
21  22  朱彥志   85   73  89  76   71  394  78.8
22  23  王良斌   60   85  88  74  100  407  81.4
23  24  陳建香   62   56  69  93   60  340  68.0
24  25  林志喜   87   63  85  99   65  399  79.8
25  26  程玫靖   52   98  73  88   91  402  80.4
26  27  楊易政   87   90  79  96   85  437  87.4
27  28  李慈啟   53   81  61  58   64  317  63.4
28  29  陳奇瑄   61   72  69  84   82  368  73.6
29  30  梁柏宇   63   82  52  83   68  348  69.6
30  31  白美珍  100   79  66  82   92  419  83.8
31  32  錢佩豪   65   54  66  67   51  303  60.6
32  33  艾巧夫   73   71  98  93   84  419  83.8
33  34  藍姿婷   85   83  64  53   63  348  69.6
34  35  陳冠竹  100   82  82  89   64  417  83.4
35  36  高智超   51   67  82  53   77  330  66.0
36  37  陳得映   77   83  53  60   92  365  73.0
37  38  景歡燦   64   95  50  91   65  365  73.0
38  39  邱亭君   78   84  62  65   54  343  68.6
39  40  賴佳雯   96   65  76  58   88  383  76.6
40  41  白美珍   85   83  68  83   60  379  75.8
41  42  林珈發   51   98  87  59   86  381  76.2
42  43  李佳彥   66   84  72  75   58  355  71.0
43  44  林玉佩   87   56  95  90  100  428  85.6
44  45  蘇婷婷   62  100  53  68   92  375  75.0
45  46  林益妏   87   78  69  53   97  384  76.8
46  47  高信宏   88   56  79  89   86  398  79.6
47  48  郭坤花   54   75  68  70   88  355  71.0
48  49  尚偉倫   76  100  76  79   77  408  81.6
49  50  謝哲維   68   61  68  90   57  344  68.8

In [4]:
df[['姓名','國','英','數']]

     姓名    國    英   數
0   王德城   99   56  67
1   游詩亞   80   67  90
2   李佳彥   63   70  51
3   陳倩潔   65   97  56
4   林向鈺   88   90  93
5   黃佩芬   77   73  98
6   楊健麟   95   89  54
7   陳信宏   80   66  64
8   白美珍   84   92  64
9   黃嘉琪   82   98  86
10  陳文賢   59   87  69
11  陳家年   76  100  61
12  錢佩豪   57   58  71
13  鄭佳玲   83   59  96
14  蔡嘉音   92   50  68
15  魏秋萍   89  100  82
16  鞠冠宇   54   91  71
17  李慈啟   86   90  66
18  楊綺芬   61   78  97
19  鄭奇翰   58   76  51
20  林俊翔   64   99  60
21  朱彥志   85   73  89
22  王良斌   60   85  88
23  陳建香   62   56  69
24  林志喜   87   63  85
25  程玫靖   52   98  73
26  楊易政   87   90  79
27  李慈啟   53   81  61
28  陳奇瑄   61   72  69
29  梁柏宇   63   82  52
30  白美珍  100   79  66
31  錢佩豪   65   54  66
32  艾巧夫   73   71  98
33  藍姿婷   85   83  64
34  陳冠竹  100   82  82
35  高智超   51   67  82
36  陳得映   77   83  53
37  景歡燦   64   95  50
38  邱亭君   78   84  62
39  賴佳雯   96   65  76
40  白美珍   85   83  68
41  林珈發   51   98  87
42  李佳彥   66   84  72
43  林玉佩   87   56  95
44  蘇婷婷   62  100  53
45  林益妏   87   78  69
46  高信宏   88   56  79
47  郭坤花   54   75  68
48  尚偉倫   76  100  76
49  謝哲維   68   61  68

In [6]:
#iloc[]     索引編號搜尋
#loc[]      索引搜尋
df.iloc[0]

學號       1
姓名     王德城
國       99
英       56
數       67
社       85
自       78
總分     385
平均    77.0
Name: 0, dtype: object

In [7]:
df.iloc[[1,3,5]]

   學號   姓名   國   英   數   社    自   總分    平均
1   2  游詩亞  80  67  90  97   51  385  77.0
3   4  陳倩潔  65  97  56  58   69  345  69.0
5   6  黃佩芬  77  73  98  55  100  403  80.6

In [8]:
df.iloc[0:6]

   學號   姓名   國   英   數   社    自   總分    平均
0   1  王德城  99  56  67  85   78  385  77.0
1   2  游詩亞  80  67  90  97   51  385  77.0
2   3  李佳彥  63  70  51  90   87  361  72.2
3   4  陳倩潔  65  97  56  58   69  345  69.0
4   5  林向鈺  88  90  93  54   71  396  79.2
5   6  黃佩芬  77  73  98  55  100  403  80.6

In [9]:
#同時要欄和列
#iloc[],loc[]
df.iloc[:5,[0,1,3]]

   學號   姓名   英
0   1  王德城  56
1   2  游詩亞  67
2   3  李佳彥  70
3   4  陳倩潔  97
4   5  林向鈺  90

In [12]:
df.loc[:5,['姓名','社','學號']]

    姓名   社  學號
0  王德城  85   1
1  游詩亞  97   2
2  李佳彥  90   3
3  陳倩潔  58   4
4  林向鈺  54   5
5  黃佩芬  55   6